### ISSUE TITLE
Log file trace messages

### ISSUE THREAD

**Issue by ikb42** [issacg/memoizee-newrelic#1]
Hi there
Thanks very much for this plug-in!
I notice TRACE entries in the log file, are there a debug thing or are they in some way required?

**Comment by issacg** [comment]
They are debug.  I (Wrongly) thought that log4js defaulted to not showing TRACE level messages, and thus a nice way of providing debug info to module users who want it but not by default, but a quick peek at the source there shows that I'm wrong.

I completely dropped the logging support for now in v0.2.3
