### ISSUE TITLE
Naming functions possible?

### ISSUE THREAD

**Issue by ikb42** [issacg/memoizee-newrelic#2]
In NewRelic, the Metric(s) list has things like:

_Component/Memoize/Functions/at Object.<anonymous> (\app......:xx:yy)_

Is it possible to name the function via a different invocation perhaps in the code or an option to Memoizee?

**Comment by issacg** [comment]
Unfortunately, this is something that memoizee provides.  Basically, it tries to find the wrapped function by looking at the call stack and moving down a few positions.

In any case, the change, if made directly on memoizee, would reflect automatically in newrelic without changes needed in memoizee-newrelic
